### ISSUE TITLE
Archived reports getting retreived without metadata stating it should be archived

### ISSUE THREAD

**Issue by MerijnDriessen** [castoredc/castoRedc#17]
The getReportInstancesBulk() function returns archived columns, which can be dangerous when researchers don't notice.
Could a filter be added to make sure archived reports are no longer retrieved?

The "study/{study_id}/report-instance" endpoint contains an archived variable, but the getReportInstanceMetadata() that is used to retrieve from that endpoint has hardcoded column selection, where archived is not (yet) selected. (https://github.com/castoredc/castoRedc/blob/dccf14444ed0e2ec8565cfbbfd46fbaf87551850/R/CastorData.R#L273)

If you select the archived column, it could be used to filter the archived reports out of the data. 

Thanks in advance

**Comment by reiniervlinschoten** [comment]
I know this is quite late, but I just started working on this package. 
I am going to look at this, and also why currently getReportInstancesBulk() fails with a join error when calling it just with a studyID

**Comment by djcher** [comment]
Hi from the US. i see the same error when I do getReportInstancesBulk(). The error message is: Error in `left_join()`:
! `by` must be supplied when `x` and `y` have no common variables.
ℹ Use `cross_join()` to perform a cross-join.

**Comment by reiniervlinschoten** [comment]
Is fixed in [v2.0.0](https://github.com/castoredc/castoRedc/tree/v2.0.0)

**Comment by djcher** [comment]
Reinier, thanks for working on this. Unfortunately, I still see the error when I run it on my us.castoredc.com-hosted study.

castor_api$getReportInstancesBulk(study_id_=STACI_ID)
Error in `left_join()`:
! `by` must be supplied when `x` and `y` have no common variables.
ℹ Use `cross_join()` to perform a cross-join.
Run `rlang::last_trace()` to see where the error occurred.


 rlang::last_trace()
<error/rlang_error>
Error in `left_join()`:
! `by` must be supplied when `x` and `y` have no common variables.
ℹ Use `cross_join()` to perform a cross-join.
---
Backtrace:
    ▆
 1. └─castor_api$getReportInstancesBulk(study_id_ = STACI_ID)
 2.   ├─dplyr::left_join(...)
 3.   └─dplyr:::left_join.data.frame(...)
Run rlang::last_trace(drop = FALSE) to see 3 hidden frames.  

Error in `left_join()`:
! `by` must be supplied when `x` and `y` have no common variables.
ℹ Use `cross_join()` to perform a cross-join.
---
Backtrace:
    ▆
 1. └─castor_api$getReportInstancesBulk(study_id_ = STACI_ID)
 2.   ├─dplyr::left_join(...)
 3.   └─dplyr:::left_join.data.frame(...)
 4.     └─dplyr:::join_mutate(...)
 5.       └─dplyr:::join_by_common(x_names, y_names, error_call = error_call)
 6.         └─rlang::abort(message, call = error_call)

**Comment by reiniervlinschoten** [comment]
Did you update the package? V2.0.0 is not on production yet, you can try:

***@***.***")


Op zo 28 jan 2024 18:43 schreef djcher ***@***.***>:

**Comment by djcher** [comment]
Hi Reinier. That could be it. I reinstalled as shown below. I see " building 'castoRedc_1.1.0.tar.gz", which means I'm likely doing something wrong. Not sure I understand your note: ***@***.***


remotes::install_github("castoredc/castoRedc", force=TRUE)


Downloading GitHub repo castoredc/castoRedc@HEAD
── R CMD build ────────────────────────────────────────────────────────────────────────────────────────────────────────
WARNING: Rtools is required to build R packages, but is not currently installed.

Please download and install Rtools 4.2 from https://cran.r-project.org/bin/windows/Rtools/ or https://www.r-project.org/nosvn/winutf8/ucrt3/.
✔  checking for file 'C:\Users\djche\AppData\Local\Temp\RtmpcpyRJ8\remotes4fdc3f08488\castoredc-castoRedc-c0bf07b/DESCRIPTION' ...
─  preparing 'castoRedc':
✔  checking DESCRIPTION meta-information ... 
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted 'LazyData' from DESCRIPTION
─  building 'castoRedc_1.1.0.tar.gz'
   
Installing package into ‘C:/Users/djche/AppData/Local/R/win-library/4.2’
(as ‘lib’ is unspecified)
* installing *source* package 'castoRedc' ...
** using staged installation
** R
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded from temporary location
** testing if installed package can be loaded from final location
** testing if installed package keeps a record of temporary installation path
* DONE (castoRedc)

**Comment by djcher** [comment]
I tried this:

remotes::install_github("castoredc/castoRedc@v2.0.0", force=TRUE)

It doesn't seem to pull 2.0.0.

Keep in mind: I'm not an expert on github... might not know what I'm doing here.

**Comment by reiniervlinschoten** [comment]
Yeah, I see Github blocks out things with a @ in them..
I see that ```remotes::install_github("castoredc/castoRedc@v2.0.0", force=TRUE)``` gives the following output:
```r
── R CMD build ─────────────────────────────────────────────────────────────────────────────────────────────────
✔  checking for file ‘/tmp/Rtmpe2gn1p/remotes119374d79ab/castoredc-castoRedc-fe63c40/DESCRIPTION’ ...
─  preparing ‘castoRedc’:
✔  checking DESCRIPTION meta-information
─  checking for LF line-endings in source and make files and shell scripts
─  checking for empty or unneeded directories
   Omitted ‘LazyData’ from DESCRIPTION
─  building ‘castoRedc_1.1.0.tar.gz’
   Warning: invalid uid value replaced by that for user 'nobody'
```

But even though it says ```─  building ‘castoRedc_1.1.0.tar.gz’``` I can then load the library and pull my RepeatingDataInstances without an error.
```r
> library(castoRedc)
> castor_api <- CastorData$new(key = "CENSORED, 
+                              secret = "CENSORED", 
+                              base_url = "https://data.castoredc.com")
> castor_api$getRepeatingDataInstancesBulk("CENSORED")
```

Maybe try the below code, and try to call your repeating data again?
```r
remove.packages("castoRedc")
remotes::install_github("castoredc/castoRedc", ref="v2.0.0", force=T)
```

**Comment by djcher** [comment]
Success! I did the following, and it worked. Previously, I was using "getReportInstancesBulk", which may not exist anymore.


remove.packages("castoRedc")
remotes::install_github("castoredc/castoRedc", ref="v2.0.0", force=TRUE)


library(castoRedc)
library(tidyverse)
castor_api <- CastorData$new(key = client_id, 
                              secret = client_secret,
                              base_url = "https://us.castoredc.com")
repeatdata=castor_api$getRepeatingDataInstancesBulk(STACI_ID)
group_by(repeatdata,repeating_data_name) %>% summarise(n=n())

surv=castor_api$getSurveyInstancesBulk(STACI_ID)
group_by(surv,package_name) %>% summarise(n=n())
